# Generated by Django 5.2.5 on 2025-09-25 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenido", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flyer",
            options={"verbose_name_plural": "Flyers de Inicio/Home"},
        ),
        migrations.AlterModelOptions(
            name="gallery",
            options={"verbose_name_plural": "Galeria de Inicio/Home"},
        ),
    ]
