# Generated by Django 5.2.3 on 2025-10-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactoStatic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo_superior",
                    models.CharField(default="Contactar con", max_length=100),
                ),
                (
                    "titulo",
                    models.CharField(default="Ecoaldea Chambalabamba", max_length=100),
                ),
                (
                    "blockquote_text",
                    models.TextField(
                        default="¿Tienes una semilla que quieras plantar con nosotros? Leeremos con atención tu mensaje y te responderemos con amor. ¡Gracias por acercarte a sembrar con nosotros!"
                    ),
                ),
                (
                    "blockquote_footer",
                    models.CharField(default="Ecoaldea Chambalabamba", max_length=100),
                ),
                (
                    "direccion",
                    models.CharField(
                        default="Via a Yamburara Alto, Vilcambamba, Ecuador",
                        max_length=200,
                    ),
                ),
                ("telefono", models.CharField(default="+593980290103", max_length=20)),
                (
                    "email",
                    models.EmailField(
                        default="info@ecoaldeachambalabamba.org", max_length=254
                    ),
                ),
                (
                    "google_maps_iframe",
                    models.TextField(
                        default='<iframe src="https.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4667.746564849565!2d-79.20696632433055!3d-4.273985246192333!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x91cb2883c3dd5ff3%3A0x43f682d79e2d2dca!2sChambalabamba-Comunidad!5e1!3m2!1ses!2sde!4v1751679359755!5m2!1ses!2sde" allowfullscreen loading="lazy"></iframe>'
                    ),
                ),
            ],
            options={
                "verbose_name": "Página de Contacto",
                "verbose_name_plural": "Páginas de Contacto",
            },
        ),
    ]
