# Generated by Django 5.2.5 on 2025-11-04 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contacto", "0002_contactostatic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactostatic",
            options={
                "verbose_name": "Página de Contacto",
                "verbose_name_plural": "Página de Contacto",
            },
        ),
    ]
