# Generated by Django 5.2.3 on 2025-08-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taller",
            name="image",
            field=models.ImageField(upload_to="talleres", verbose_name="Imagen"),
        ),
    ]
