# Generated by Django 5.2.3 on 2025-09-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0006_festivalesheader_festivalesintrosection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="festival",
            name="flyer",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="festivales/flyers",
                verbose_name="Flyer",
            ),
        ),
        migrations.AlterField(
            model_name="festival",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="festivales", verbose_name="Imagen"
            ),
        ),
    ]
