# Generated by Django 5.2.3 on 2025-09-10 20:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0007_festival_flyer_alter_festival_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="festival",
            options={
                "verbose_name": "Sección: Lista de Festivales",
                "verbose_name_plural": "Sección: Lista de Festivales",
            },
        ),
    ]
