# Generated by Django 5.2.5 on 2025-10-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PageHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(blank=True, default="", max_length=150)),
                ("subtitle", models.CharField(blank=True, default="", max_length=200)),
                (
                    "background",
                    models.ImageField(blank=True, null=True, upload_to="headers/"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
