# Generated by Django 5.2.5 on 2025-09-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autenticacion", "0003_populate_tipousuario_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipousuario",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Identificador único (ej. 'externo', 'residente').",
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
    ]
