# Generated by Django 5.2.5 on 2025-11-04 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("donaciones", "0006_donacionesstatic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donacionesstatic",
            options={
                "verbose_name": "Página de Donaciones",
                "verbose_name_plural": "Páginas de Donaciones",
            },
        ),
    ]
