# Generated by Django 5.2.5 on 2025-09-23 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitas", "0002_alter_guidedvisit_actualizado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitslanding",
            name="intro_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="visitas/landing/"
            ),
        ),
        migrations.AlterField(
            model_name="guidedvisit",
            name="actualizado",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 9, 23, 16, 36, 58, 599993, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="guidedvisit",
            name="creado",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 9, 23, 16, 36, 58, 599975, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="guidedvisitphoto",
            name="actualizado",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 9, 23, 16, 36, 58, 600802, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="guidedvisitphoto",
            name="creado",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 9, 23, 16, 36, 58, 600782, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="visitslanding",
            name="actualizado",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 9, 23, 16, 36, 58, 599168, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
