# Generated by Django 5.2.5 on 2025-09-24 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitas", "0005_alter_guidedvisit_actualizado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidedvisit",
            name="actualizado",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 9, 24, 21, 43, 30, 597670, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="guidedvisit",
            name="creado",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 9, 24, 21, 43, 30, 597656, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="guidedvisitphoto",
            name="actualizado",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 9, 24, 21, 43, 30, 598230, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="guidedvisitphoto",
            name="creado",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 9, 24, 21, 43, 30, 598213, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="visitslanding",
            name="actualizado",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 9, 24, 21, 43, 30, 597092, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
