# Generated by Django 5.2.5 on 2025-09-24 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitas", "0006_alter_guidedvisit_actualizado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidedvisit",
            name="actualizado",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 9, 24, 21, 55, 46, 119240, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="guidedvisit",
            name="creado",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 9, 24, 21, 55, 46, 119217, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="guidedvisitphoto",
            name="actualizado",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 9, 24, 21, 55, 46, 120053, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="guidedvisitphoto",
            name="creado",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 9, 24, 21, 55, 46, 120033, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="visitslanding",
            name="actualizado",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 9, 24, 21, 55, 46, 118412, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
