# Generated by Django 5.2.5 on 2025-09-25 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitas", "0014_alter_guidedvisit_actualizado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidedvisit",
            name="actualizado",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 9, 25, 16, 52, 42, 191740, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="guidedvisit",
            name="creado",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 9, 25, 16, 52, 42, 191720, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="guidedvisitphoto",
            name="actualizado",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 9, 25, 16, 52, 42, 192605, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="guidedvisitphoto",
            name="creado",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 9, 25, 16, 52, 42, 192584, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="visitslanding",
            name="actualizado",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 9, 25, 16, 52, 42, 190835, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
