# Generated by Django 5.2.5 on 2025-09-29 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitas", "0019_alter_guidedvisit_actualizado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidedvisit",
            name="actualizado",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 9, 29, 17, 42, 3, 551853, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="guidedvisit",
            name="creado",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 9, 29, 17, 42, 3, 551833, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="guidedvisitphoto",
            name="actualizado",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 9, 29, 17, 42, 3, 552663, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="guidedvisitphoto",
            name="creado",
            field=models.DateTimeField(
                auto_now_add=True,
                db_default=datetime.datetime(
                    2025, 9, 29, 17, 42, 3, 552641, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="visitslanding",
            name="actualizado",
            field=models.DateTimeField(
                auto_now=True,
                db_default=datetime.datetime(
                    2025, 9, 29, 17, 42, 3, 550986, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
