# Generated by Django 5.2.5 on 2025-10-10 22:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("visitas", "0022_alter_guidedvisit_actualizado_and_more"),
        ("visitas", "0022_pageheader_alter_guidedvisit_actualizado_and_more"),
    ]

    operations = []
