# Generated by Django 5.2.5 on 2025-09-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publicado", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=150)),
                ("subtitulo", models.CharField(blank=True, max_length=250)),
                ("boton1_texto", models.CharField(blank=True, max_length=40)),
                ("boton1_url", models.URLField(blank=True)),
                ("boton2_texto", models.CharField(blank=True, max_length=40)),
                ("boton2_url", models.URLField(blank=True)),
                ("imagen", models.ImageField(upload_to="inicio/hero/")),
            ],
            options={
                "ordering": ["orden", "-creado"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InstaFoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publicado", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("imagen", models.ImageField(upload_to="images/galerias/")),
                ("alt", models.CharField(blank=True, max_length=160)),
                ("enlace", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["orden", "-creado"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publicado", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=100)),
                ("imagen", models.ImageField(upload_to="inicio/productos/")),
                (
                    "precio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "precio_tachado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["orden", "-creado"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProyectoCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publicado", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=120)),
                ("resumen", models.CharField(blank=True, max_length=220)),
                ("imagen", models.ImageField(upload_to="inicio/proyectos/")),
                ("url", models.URLField(blank=True)),
                ("etiqueta", models.CharField(blank=True, max_length=30)),
            ],
            options={
                "ordering": ["orden", "-creado"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ValorCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publicado", models.BooleanField(default=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=80)),
                ("descripcion", models.CharField(blank=True, max_length=200)),
                (
                    "icono",
                    models.ImageField(blank=True, null=True, upload_to="inicio/icons/"),
                ),
                ("slug", models.SlugField(blank=True, max_length=90, unique=True)),
            ],
            options={
                "ordering": ["orden", "-creado"],
                "abstract": False,
            },
        ),
    ]
