# Generated by Django 5.2.5 on 2025-09-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inicio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instafoto",
            name="imagen",
            field=models.ImageField(upload_to="inicio/galerias/"),
        ),
    ]
