# Generated by Django 5.2.5 on 2025-09-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inicio", "0010_alter_gallery_seccion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="seccion",
            field=models.CharField(
                choices=[
                    ("home_ultimos_evento", "Home – Ultimos-Eventos"),
                    ("nosotros_cabecera", "Nosotros – Cabecera"),
                    ("proyectos_movimiento", "Home – Proyecto movimiento"),
                    ("participa_estancias", "Participa – Estancias"),
                ],
                default="home_ultimo_evento",
                max_length=50,
            ),
        ),
    ]
