# Generated by Django 5.2.5 on 2025-09-08 03:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inicio", "0012_alter_gallery_seccion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="heroslide",
            options={
                "ordering": ["orden", "-creado"],
                "verbose_name": "Cabecera",
                "verbose_name_plural": "Cabeceras",
            },
        ),
    ]
