# Generated by Django 5.2.5 on 2025-09-08 03:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inicio", "0013_alter_heroslide_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProyectoCard",
        ),
        migrations.AlterModelOptions(
            name="valorcard",
            options={
                "ordering": ["orden", "-creado"],
                "verbose_name": "Pilares",
                "verbose_name_plural": "Pilares",
            },
        ),
    ]
