# Generated by Django 5.2.5 on 2025-09-08 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inicio", "0016_alter_gallery_options_alter_heroslide_options_and_more"),
    ]

    operations = []
