# Generated by Django 5.2.5 on 2025-09-09 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inicio", "0017_rename_portadas_gallery_portada"),
    ]

    operations = []
