# Generated by Django 5.2.5 on 2025-09-09 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inicio", "0018_rename_portadas_gallery_portada"),
    ]

    operations = []
