# Generated by Django 5.2.5 on 2025-09-11 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inicio", "0019_rename_portadas_gallery_portada"),
    ]

    operations = [
        # Nada en DB porque ya está renombrado
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameField(
                    model_name="gallery",
                    old_name="portadas",
                    new_name="portada",
                ),
            ],
        ),
    ]
