# Generated by Django 5.2.5 on 2025-11-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inicio", "0023_alter_sectionheader_seccion"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionheader",
            name="limit",
            field=models.PositiveSmallIntegerField(default=12),
        ),
    ]
