# Generated by Django 5.2.5 on 2025-12-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inicio", "0024_sectionheader_limit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery",
            options={
                "ordering": ["-orden", "-creado"],
                "verbose_name": "3. Galerías / Galleries",
                "verbose_name_plural": "3. Galerías / Galleries",
            },
        ),
        migrations.AlterField(
            model_name="sectionheader",
            name="seccion",
            field=models.CharField(
                choices=[
                    ("home_ultimos_eventos", "Home – Últimos Eventos"),
                    ("nosotros_cabecera", "Nosotros – Cabecera"),
                    ("proyectos_movimiento", "Home – Proyectos en Movimiento"),
                    ("participa_estancias", "Participa – Estancias"),
                    ("tienda_tabs", "Tienda – Tabs"),
                    ("home_cooperaciones", "cooperaciones – Tabs"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
