# Generated by Django 5.2.5 on 2026-01-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inicio", "0025_alter_gallery_options_alter_sectionheader_seccion"),
    ]

    operations = [
        migrations.AddField(
            model_name="valorcard",
            name="link_url",
            field=models.URLField(
                blank=True, help_text="URL a donde debe llevar este pilar (opcional)."
            ),
        ),
    ]
