# Generated by Django 5.2.5 on 2025-09-25 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="categorias",
        ),
        migrations.RemoveField(
            model_name="post",
            name="autor",
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
