# Generated by Django 5.2.5 on 2025-09-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_blogcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogheader",
            name="breadcrumb_label",
            field=models.CharField(default="Blog-Detail", max_length=120),
        ),
    ]
