# Generated by Django 5.2.5 on 2025-09-09 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nosotros", "0004_pilarpage_pilarproyecto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pilarproyecto",
            name="pilar",
        ),
        migrations.DeleteModel(
            name="PilarPage",
        ),
        migrations.DeleteModel(
            name="PilarProyecto",
        ),
    ]
