# Generated by Django 5.2.5 on 2025-09-08 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("participa", "0003_instagallery_instaitem"),
    ]

    operations = []
