# Generated by Django 5.2.5 on 2025-09-09 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("participa", "0005_rename_portadas_estancia_portada"),
    ]

    operations = []
