# Generated by Django 5.2.5 on 2025-09-11 15:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("participa", "0006_rename_portadas_estancia_portada"),
    ]

    operations = [
        # Rename the field in both the database and Django's state
        migrations.RenameField(
            model_name="estancia",
            old_name="portadas",
            new_name="portada",
        ),
    ]
