# Generated by Django 5.2.5 on 2025-09-23 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("participa", "0015_innerheader"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BreadcrumbItem",
        ),
        migrations.RemoveField(
            model_name="guidedvisitphoto",
            name="visita",
        ),
        migrations.DeleteModel(
            name="InnerHeader",
        ),
        migrations.RemoveField(
            model_name="guidedvisitspage",
            name="breadcrumb_slug",
        ),
        migrations.DeleteModel(
            name="GuidedVisit",
        ),
        migrations.DeleteModel(
            name="GuidedVisitPhoto",
        ),
    ]
